### PR TITLE
Some initial content changes

### PR DESCRIPTION
**Pull request by aedobbyn**
I only changed index.html, not index.xml here (not sure which one is derived from which).

### CODE REVIEW

**Comment by pachamaltese** [comment]
Awesome! Thanks!
The xml comes after the html
I'll do the rsync thing when I get home

**Comment by aedobbyn** [comment]
Sounds good!

**Comment by pachamaltese** [comment]
thanks a lot @aedobbyn !! I just merged the PR and synced the server

**Comment by aedobbyn** [comment]
Great! Will push to the same branch and open a new PR if I see anything else to change.

**Comment by pachamaltese** [comment]
Cool. I moved your changes to index to themes/ so that hugo builds won't
remove them

**Pull request merged**
